/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MemeRouteImport } from './routes/meme'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoastRouteImport } from './routes/roast'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemeRoute = MemeRouteImport.update({
  id: '/meme',
  path: '/meme',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastRoute = RoastRouteImport.update({
  id: '/roast',
  path: '/roast',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/chat': typeof ChatRoute
  '/hub': typeof HubRoute
  '/leaderboard': typeof LeaderboardRoute
  '/meme': typeof MemeRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/chat': typeof ChatRoute
  '/hub': typeof HubRoute
  '/leaderboard': typeof LeaderboardRoute
  '/meme': typeof MemeRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/chat': typeof ChatRoute
  '/hub': typeof HubRoute
  '/leaderboard': typeof LeaderboardRoute
  '/meme': typeof MemeRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arcade'
    | '/chat'
    | '/hub'
    | '/leaderboard'
    | '/meme'
    | '/profile'
    | '/roast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arcade'
    | '/chat'
    | '/hub'
    | '/leaderboard'
    | '/meme'
    | '/profile'
    | '/roast'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arcade'
    | '/chat'
    | '/hub'
    | '/leaderboard'
    | '/meme'
    | '/profile'
    | '/roast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArcadeRoute: typeof ArcadeRoute
  ChatRoute: typeof ChatRoute
  HubRoute: typeof HubRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MemeRoute: typeof MemeRoute
  ProfileRoute: typeof ProfileRoute
  RoastRoute: typeof RoastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meme': {
      id: '/meme'
      path: '/meme'
      fullPath: '/meme'
      preLoaderRoute: typeof MemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roast': {
      id: '/roast'
      path: '/roast'
      fullPath: '/roast'
      preLoaderRoute: typeof RoastRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArcadeRoute: ArcadeRoute,
  ChatRoute: ChatRoute,
  HubRoute: HubRoute,
  LeaderboardRoute: LeaderboardRoute,
  MemeRoute: MemeRoute,
  ProfileRoute: ProfileRoute,
  RoastRoute: RoastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
