/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BuildersRouteImport } from './routes/builders'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CommunityCityRouteImport } from './routes/community-city'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MemeRouteImport } from './routes/meme'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoastRouteImport } from './routes/roast'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BuilderUsernameRouteImport } from './routes/builder/$username'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as EcosystemProjectSlugRouteImport } from './routes/ecosystem-project.$slug'
import { Route as ApiPublicPerpsTestRouteImport } from './routes/api/public/perps-test'
import { Route as ApiPublicXMentionRouteImport } from './routes/api/public/x-mention'
import { Route as ApiPublicXPollRouteImport } from './routes/api/public/x-poll'
import { Route as OauthGithubReturnRouteImport } from './routes/oauth/github/return'
import { Route as OauthXReturnRouteImport } from './routes/oauth/x/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersRoute = BuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCityRoute = CommunityCityRouteImport.update({
  id: '/community-city',
  path: '/community-city',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MemeRoute = MemeRouteImport.update({
  id: '/meme',
  path: '/meme',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastRoute = RoastRouteImport.update({
  id: '/roast',
  path: '/roast',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuilderUsernameRoute = BuilderUsernameRouteImport.update({
  id: '/builder/$username',
  path: '/builder/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemProjectSlugRoute = EcosystemProjectSlugRouteImport.update({
  id: '/ecosystem-project/$slug',
  path: '/ecosystem-project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPerpsTestRoute = ApiPublicPerpsTestRouteImport.update({
  id: '/api/public/perps-test',
  path: '/api/public/perps-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXMentionRoute = ApiPublicXMentionRouteImport.update({
  id: '/api/public/x-mention',
  path: '/api/public/x-mention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXPollRoute = ApiPublicXPollRouteImport.update({
  id: '/api/public/x-poll',
  path: '/api/public/x-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGithubReturnRoute = OauthGithubReturnRouteImport.update({
  id: '/oauth/github/return',
  path: '/oauth/github/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthXReturnRoute = OauthXReturnRouteImport.update({
  id: '/oauth/x/return',
  path: '/oauth/x/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/build': typeof BuildRoute
  '/builders': typeof BuildersRoute
  '/chat': typeof ChatRoute
  '/community-city': typeof CommunityCityRoute
  '/ecosystem': typeof EcosystemRoute
  '/how-to-play': typeof HowToPlayRoute
  '/hub': typeof HubRoute
  '/launches': typeof LaunchesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/meme': typeof MemeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/builder/$username': typeof BuilderUsernameRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/ecosystem-project/$slug': typeof EcosystemProjectSlugRoute
  '/api/public/perps-test': typeof ApiPublicPerpsTestRoute
  '/api/public/x-mention': typeof ApiPublicXMentionRoute
  '/api/public/x-poll': typeof ApiPublicXPollRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
  '/oauth/x/return': typeof OauthXReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/build': typeof BuildRoute
  '/builders': typeof BuildersRoute
  '/chat': typeof ChatRoute
  '/community-city': typeof CommunityCityRoute
  '/ecosystem': typeof EcosystemRoute
  '/how-to-play': typeof HowToPlayRoute
  '/hub': typeof HubRoute
  '/launches': typeof LaunchesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/meme': typeof MemeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/builder/$username': typeof BuilderUsernameRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/ecosystem-project/$slug': typeof EcosystemProjectSlugRoute
  '/api/public/perps-test': typeof ApiPublicPerpsTestRoute
  '/api/public/x-mention': typeof ApiPublicXMentionRoute
  '/api/public/x-poll': typeof ApiPublicXPollRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
  '/oauth/x/return': typeof OauthXReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/build': typeof BuildRoute
  '/builders': typeof BuildersRoute
  '/chat': typeof ChatRoute
  '/community-city': typeof CommunityCityRoute
  '/ecosystem': typeof EcosystemRoute
  '/how-to-play': typeof HowToPlayRoute
  '/hub': typeof HubRoute
  '/launches': typeof LaunchesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/meme': typeof MemeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/builder/$username': typeof BuilderUsernameRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/ecosystem-project/$slug': typeof EcosystemProjectSlugRoute
  '/api/public/perps-test': typeof ApiPublicPerpsTestRoute
  '/api/public/x-mention': typeof ApiPublicXMentionRoute
  '/api/public/x-poll': typeof ApiPublicXPollRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
  '/oauth/x/return': typeof OauthXReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arcade'
    | '/build'
    | '/builders'
    | '/chat'
    | '/community-city'
    | '/ecosystem'
    | '/how-to-play'
    | '/hub'
    | '/launches'
    | '/leaderboard'
    | '/mcp'
    | '/meme'
    | '/privacy'
    | '/profile'
    | '/roast'
    | '/sitemap.xml'
    | '/terminal'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/builder/$username'
    | '/claim/$token'
    | '/ecosystem-project/$slug'
    | '/api/public/perps-test'
    | '/api/public/x-mention'
    | '/api/public/x-poll'
    | '/oauth/github/return'
    | '/oauth/x/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arcade'
    | '/build'
    | '/builders'
    | '/chat'
    | '/community-city'
    | '/ecosystem'
    | '/how-to-play'
    | '/hub'
    | '/launches'
    | '/leaderboard'
    | '/mcp'
    | '/meme'
    | '/privacy'
    | '/profile'
    | '/roast'
    | '/sitemap.xml'
    | '/terminal'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/builder/$username'
    | '/claim/$token'
    | '/ecosystem-project/$slug'
    | '/api/public/perps-test'
    | '/api/public/x-mention'
    | '/api/public/x-poll'
    | '/oauth/github/return'
    | '/oauth/x/return'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arcade'
    | '/build'
    | '/builders'
    | '/chat'
    | '/community-city'
    | '/ecosystem'
    | '/how-to-play'
    | '/hub'
    | '/launches'
    | '/leaderboard'
    | '/mcp'
    | '/meme'
    | '/privacy'
    | '/profile'
    | '/roast'
    | '/sitemap.xml'
    | '/terminal'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/builder/$username'
    | '/claim/$token'
    | '/ecosystem-project/$slug'
    | '/api/public/perps-test'
    | '/api/public/x-mention'
    | '/api/public/x-poll'
    | '/oauth/github/return'
    | '/oauth/x/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArcadeRoute: typeof ArcadeRoute
  BuildRoute: typeof BuildRoute
  BuildersRoute: typeof BuildersRoute
  ChatRoute: typeof ChatRoute
  CommunityCityRoute: typeof CommunityCityRoute
  EcosystemRoute: typeof EcosystemRoute
  HowToPlayRoute: typeof HowToPlayRoute
  HubRoute: typeof HubRoute
  LaunchesRoute: typeof LaunchesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  McpRoute: typeof McpRoute
  MemeRoute: typeof MemeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RoastRoute: typeof RoastRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminalRoute: typeof TerminalRoute
  TermsRoute: typeof TermsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BuilderUsernameRoute: typeof BuilderUsernameRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  EcosystemProjectSlugRoute: typeof EcosystemProjectSlugRoute
  ApiPublicPerpsTestRoute: typeof ApiPublicPerpsTestRoute
  ApiPublicXMentionRoute: typeof ApiPublicXMentionRoute
  ApiPublicXPollRoute: typeof ApiPublicXPollRoute
  OauthGithubReturnRoute: typeof OauthGithubReturnRoute
  OauthXReturnRoute: typeof OauthXReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders': {
      id: '/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof BuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-city': {
      id: '/community-city'
      path: '/community-city'
      fullPath: '/community-city'
      preLoaderRoute: typeof CommunityCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meme': {
      id: '/meme'
      path: '/meme'
      fullPath: '/meme'
      preLoaderRoute: typeof MemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roast': {
      id: '/roast'
      path: '/roast'
      fullPath: '/roast'
      preLoaderRoute: typeof RoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$username': {
      id: '/builder/$username'
      path: '/builder/$username'
      fullPath: '/builder/$username'
      preLoaderRoute: typeof BuilderUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem-project/$slug': {
      id: '/ecosystem-project/$slug'
      path: '/ecosystem-project/$slug'
      fullPath: '/ecosystem-project/$slug'
      preLoaderRoute: typeof EcosystemProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/perps-test': {
      id: '/api/public/perps-test'
      path: '/api/public/perps-test'
      fullPath: '/api/public/perps-test'
      preLoaderRoute: typeof ApiPublicPerpsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x-mention': {
      id: '/api/public/x-mention'
      path: '/api/public/x-mention'
      fullPath: '/api/public/x-mention'
      preLoaderRoute: typeof ApiPublicXMentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x-poll': {
      id: '/api/public/x-poll'
      path: '/api/public/x-poll'
      fullPath: '/api/public/x-poll'
      preLoaderRoute: typeof ApiPublicXPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/github/return': {
      id: '/oauth/github/return'
      path: '/oauth/github/return'
      fullPath: '/oauth/github/return'
      preLoaderRoute: typeof OauthGithubReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/x/return': {
      id: '/oauth/x/return'
      path: '/oauth/x/return'
      fullPath: '/oauth/x/return'
      preLoaderRoute: typeof OauthXReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArcadeRoute: ArcadeRoute,
  BuildRoute: BuildRoute,
  BuildersRoute: BuildersRoute,
  ChatRoute: ChatRoute,
  CommunityCityRoute: CommunityCityRoute,
  EcosystemRoute: EcosystemRoute,
  HowToPlayRoute: HowToPlayRoute,
  HubRoute: HubRoute,
  LaunchesRoute: LaunchesRoute,
  LeaderboardRoute: LeaderboardRoute,
  McpRoute: McpRoute,
  MemeRoute: MemeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RoastRoute: RoastRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminalRoute: TerminalRoute,
  TermsRoute: TermsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BuilderUsernameRoute: BuilderUsernameRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  EcosystemProjectSlugRoute: EcosystemProjectSlugRoute,
  ApiPublicPerpsTestRoute: ApiPublicPerpsTestRoute,
  ApiPublicXMentionRoute: ApiPublicXMentionRoute,
  ApiPublicXPollRoute: ApiPublicXPollRoute,
  OauthGithubReturnRoute: OauthGithubReturnRoute,
  OauthXReturnRoute: OauthXReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
